## Implementation of Logic Gates in PyT:fire:rch

Only for **XOR**, **OR**, and **AND**! [Here](https://www.elprocus.com/basic-logic-gates-with-truth-tables/) are some simple and good explanations.

In [1]:
from typing import Union

import torch
import torch.nn as nn

<div style="color: white; display: fill; border-radius: 5px; background-color: #6905ed; font-size: 110%">
  <h2 style="padding: 15px; color: white;">Using Predefined Functions</h2>
</div>

In [2]:
data1 = torch.tensor([0, 0, 1, 1], dtype=torch.int8)
data2 = torch.tensor([0, 1, 0, 1], dtype=torch.int8)

In [3]:
torch.logical_xor(data1, data2)

tensor([False,  True,  True, False])

In [4]:
torch.logical_or(data1, data2)

tensor([False,  True,  True,  True])

In [5]:
torch.logical_and(data1, data2)

tensor([False, False, False,  True])

<div style="color: white; display: fill; border-radius: 5px; background-color: #f55925; font-size: 110%">
  <h2 style="padding: 15px; color: white;">Logistic Regression and the Module Class</h2>
</div>

In [21]:
class LogisticRegression(nn.Module):
    def __init__(self, input_dim: int, hidden_dim: int, output_dim: int) -> None:
        super(LogisticRegression, self).__init__()
        self.linear1 = nn.Linear(input_dim, hidden_dim)
        self.linear2 = nn.Linear(hidden_dim, output_dim)
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Feeds the data to the neural network."""
        output = torch.sigmoid(self.linear1(x))
        output = torch.sigmoid(self.linear2(output))
        return output

In [22]:
def train(model: Union[nn.Module, nn.Sequential], criterion: Union[nn.MSELoss, nn.BCELoss],
          optimizer: Union[torch.optim.SGD, torch.optim.Adam],
          X: torch.Tensor, y: torch.Tensor, epochs: int) -> None:
    """Trains the neural network and reports."""
    epochs_size = len(str(epochs))  # To beautify when reporting
    
    for epoch in range(epochs+1):
        y_pred = model(X)
        loss = criterion(y_pred, y)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        # Print the loss in every 5% of epochs
        if epoch % int(epochs * .05) == 0:
            print(f'[EPOCH {epoch: >{epochs_size}}/{epochs}] The loss is {loss.item():.5f}')

Adding type annotations to PyTorch is painful!

In [23]:
epochs = 40000
input_dim = 2
hidden_dim = 3
output_dim = 1
learning_rate = 1e-2

In [24]:
model_logical_xor = LogisticRegression(input_dim, hidden_dim, output_dim)
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model_logical_xor.parameters(), lr=learning_rate)

In [25]:
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
y = torch.tensor([[0], [1], [1], [0]], dtype=torch.float32)

In [27]:
train(model_logical_xor, criterion, optimizer, X, y, epochs)

[EPOCH     0/40000] The loss is 0.24826
[EPOCH  2000/40000] The loss is 0.24794
[EPOCH  4000/40000] The loss is 0.24753
[EPOCH  6000/40000] The loss is 0.24701
[EPOCH  8000/40000] The loss is 0.24635
[EPOCH 10000/40000] The loss is 0.24549
[EPOCH 12000/40000] The loss is 0.24436
[EPOCH 14000/40000] The loss is 0.24287
[EPOCH 16000/40000] The loss is 0.24089
[EPOCH 18000/40000] The loss is 0.23824
[EPOCH 20000/40000] The loss is 0.23468
[EPOCH 22000/40000] The loss is 0.22991
[EPOCH 24000/40000] The loss is 0.22357
[EPOCH 26000/40000] The loss is 0.21522
[EPOCH 28000/40000] The loss is 0.20437
[EPOCH 30000/40000] The loss is 0.19059
[EPOCH 32000/40000] The loss is 0.17375
[EPOCH 34000/40000] The loss is 0.15429
[EPOCH 36000/40000] The loss is 0.13344
[EPOCH 38000/40000] The loss is 0.11291
[EPOCH 40000/40000] The loss is 0.09425


In [38]:
model_logical_xor(X) \
    .round()

tensor([[0.],
        [1.],
        [1.],
        [0.]], grad_fn=<RoundBackward0>)

In [29]:
model_logical_or = LogisticRegression(input_dim, hidden_dim, output_dim)
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model_logical_or.parameters(), lr=learning_rate)

In [30]:
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
y = torch.tensor([[0], [1], [1], [1]], dtype=torch.float32)

In [31]:
train(model_logical_or, criterion, optimizer, X, y, epochs)

[EPOCH     0/40000] The loss is 0.33582
[EPOCH  2000/40000] The loss is 0.17480
[EPOCH  4000/40000] The loss is 0.16493
[EPOCH  6000/40000] The loss is 0.15142
[EPOCH  8000/40000] The loss is 0.13335
[EPOCH 10000/40000] The loss is 0.11128
[EPOCH 12000/40000] The loss is 0.08790
[EPOCH 14000/40000] The loss is 0.06676
[EPOCH 16000/40000] The loss is 0.04997
[EPOCH 18000/40000] The loss is 0.03765
[EPOCH 20000/40000] The loss is 0.02891
[EPOCH 22000/40000] The loss is 0.02274
[EPOCH 24000/40000] The loss is 0.01831
[EPOCH 26000/40000] The loss is 0.01506
[EPOCH 28000/40000] The loss is 0.01264
[EPOCH 30000/40000] The loss is 0.01078
[EPOCH 32000/40000] The loss is 0.00933
[EPOCH 34000/40000] The loss is 0.00817
[EPOCH 36000/40000] The loss is 0.00724
[EPOCH 38000/40000] The loss is 0.00647
[EPOCH 40000/40000] The loss is 0.00584


In [39]:
model_logical_or(X) \
    .round()

tensor([[0.],
        [1.],
        [1.],
        [1.]], grad_fn=<RoundBackward0>)

In [33]:
model_logical_and = LogisticRegression(input_dim, hidden_dim, output_dim)
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model_logical_and.parameters(), lr=learning_rate)

In [34]:
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
y = torch.tensor([[0], [0], [0], [1]], dtype=torch.float32)

In [35]:
train(model_logical_and, criterion, optimizer, X, y, epochs)

[EPOCH     0/40000] The loss is 0.32067
[EPOCH  2000/40000] The loss is 0.18755
[EPOCH  4000/40000] The loss is 0.18151
[EPOCH  6000/40000] The loss is 0.17368
[EPOCH  8000/40000] The loss is 0.16387
[EPOCH 10000/40000] The loss is 0.15249
[EPOCH 12000/40000] The loss is 0.13986
[EPOCH 14000/40000] The loss is 0.12625
[EPOCH 16000/40000] The loss is 0.11209
[EPOCH 18000/40000] The loss is 0.09789
[EPOCH 20000/40000] The loss is 0.08423
[EPOCH 22000/40000] The loss is 0.07165
[EPOCH 24000/40000] The loss is 0.06054
[EPOCH 26000/40000] The loss is 0.05104
[EPOCH 28000/40000] The loss is 0.04313
[EPOCH 30000/40000] The loss is 0.03662
[EPOCH 32000/40000] The loss is 0.03131
[EPOCH 34000/40000] The loss is 0.02699
[EPOCH 36000/40000] The loss is 0.02346
[EPOCH 38000/40000] The loss is 0.02056
[EPOCH 40000/40000] The loss is 0.01817


In [40]:
model_logical_and(X) \
    .round()

tensor([[0.],
        [0.],
        [0.],
        [1.]], grad_fn=<RoundBackward0>)